---
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - glibc_2.28
      env:
         - MATRIX_EVAL="CC=gcc-9"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-10.0
          packages:
            - clang-10.0
            - glibc_2.28
      env:
        - MATRIX_EVAL="CC=clang-10.0"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - make check
